apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-blue-blue
  labels:
    app: webapp
    harness.io/color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
      harness.io/color: blue
  template:
    metadata:
      labels:
        app: webapp
        harness.io/color: blue
    spec:
      containers:
        - name: webapp
          image: mandavikas17/webapp:2.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
