apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
      version: blue 
  template:
    metadata:
      labels:
        app: my-app
        version: blue 
    spec:
      containers:
      - name: my-app-container
        image: mandavikas17/webapp:2.0
        ports:
        - containerPort: 8080
