apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-<+service.variables.COLOR>
  labels:
    app: myapp
    version: <+service.variables.COLOR>
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: <+service.variables.COLOR>
  template:
    metadata:
      labels:
        app: myapp
        version: <+service.variables.COLOR>
    spec:
      containers:
        - name: myapp
          image: myrepo/myapp:<+service.variables.IMAGE_TAG>
          ports:
            - containerPort: 8080
