apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-<+deployment.identifier>
  labels:
    app: myapp
    version: <+deployment.identifier>
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: <+deployment.identifier>
  template:
    metadata:
      labels:
        app: myapp
        version: <+deployment.identifier>
    spec:
      containers:
        - name: myapp
          image: mandavikas17/webapp:<+service.variables.IMAGE_TAG>
          ports:
            - containerPort: 8080
