apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
spec:
  type: ClusterIP
  selector:
    app: myapp
    version: <+deployment.identifier>
  ports:
    - port: 80
      targetPort: 8080
