apiVersion: v1
kind: Service
metadata:
  name: webapp-primary-stage
  labels:
    app: webapp
spec:
  type: ClusterIP
  selector:
    app: webapp
    harness.io/color: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
