apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  type: ClusterIP 
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: my-app
    
